query summoner($region: ID!, $summonerName: String) {
  region(region: $region) {
    summonerByName(summoner: $summonerName) {
      id
      name
      summonerLevel
      profileIcon
      recentMatchlists {
        timestamp
        champion {
          name
          title
          championIcon
        }
      }
    }
  }
}